### PR TITLE
chore: add deployment script for RollerPeriphery v2

### PR DESCRIPTION
**Pull request by fedealconada**
Adding the deployment script for RollerPeriphery V2. Note that this should be ran after we've deployed the Periphery v2, and we must update the Periphery's contract address with the new one.

### CODE REVIEW

**Review by jparklev — APPROVED** [review]
We should also update the periphery address on all of the live auto rollers once we deploy. Though that'll require events so maybe do it in hardhat? 

Anyway, the changes here LGTM. ty fed

**Comment by jparklev** [comment]
> Note that this should be ran after we've deployed the Periphery v2, and we must update the Periphery's contract address with the new one.

+1! Also we should update it in the tests, and make sure that works

**Comment by fedealconada** [comment]
> We should also update the periphery address on all of the live auto rollers once we deploy. Though that'll require events so maybe do it in hardhat?
> 
> Anyway, the changes here LGTM. ty fed

right! i can actually add that to the Periphery deployment script on sense-v1 which is in hardhat

**Review by stevenvaleri — APPROVED** [review]
Looks good to me.

Reviewed the AddressBook against etherscan, and they lineup.

**Pull request merged**
